#!/usr/bin/sh

api_key='YOUR_API_KEY_HERE'
alias fzf="fzf --header-lines 1 --reverse --nth 5.. --with-nth=2.."

while getopts ":s:t:" o; do case "${o}" in
	s) search_term=${OPTARG};;
	t) tracker=${OPTARG};;
	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done

[ $OPTIND -eq 1 ] && search_term="$@"

url="http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=$api_key"

[ -n "$tracker" ] && url+="&Tracker%5B%5D=$tracker"

raw_torrents_data=$(curl -s -G --data-urlencode "Query=$search_term" $url)
torrents_data="$(jq '.Results | sort_by(.Seeders) | reverse' <<< $raw_torrents_data)"

torrents_table=$(
  echo "$torrents_data" |
  jq -r '.[] | [.Seeders, .Size, .TrackerId, .Title] | @tsv' |
  numfmt --to=iec --field 2 -d$'\t' |
  nl -v 0 -w 1 | 
  column --table-columns "ID,Seeder,Size,Tracker,Title" --table --separator $'\t'
)

selected_torrent="$(echo "$torrents_table" | fzf)"
selected_torrent_id="$(echo "$selected_torrent" | cut -d' ' -f1)"

[ -n "$selected_torrent_id" ] && (
  echo "$torrents_data" | jq -e ".[$selected_torrent_id] | select(.MagnetUri != null) | .MagnetUri" ||
  echo "$torrents_data" | jq -e ".[$selected_torrent_id] | select(.Link != null) | .Link" | xargs -r wget --server-response 2>&1 | grep 'Location:' -m 1 | sed 's|Location:||'

) | xargs -r xdg-open 2>/dev/null

