#!/usr/bin/bash

api_key='6jchchegslblfgw4kuweoyg1nohy2ngj' 
export FZF_DEFAULT_OPTS="--header-lines 1 --reverse --nth 4.. --with-nth=2.. --multi -i"

while getopts ":s:t:" o; do case "${o}" in
	s) search_term=${OPTARG};;
	t) tracker=${OPTARG};;
	*) printf "Invalid option: -%s\\n" "$OPTARG" && exit 1 ;;
esac done

[ $OPTIND -eq 1 ] && search_term="$*"
# tracker="$tracker"'1337x,rarbg'

url="http://127.0.0.1:9117/api/v2.0/indexers/all/results?apikey=$api_key"

[ -n "$tracker" ] && url="$url""&Tracker%5B%5D=$tracker"

raw_torrents_data=$(curl -s -G --data-urlencode "Query=$search_term" "$url")
torrents_data="$(echo "$raw_torrents_data" | jq '.Results | sort_by(.Seeders) | reverse')"

torrents_table=$(
  echo "$torrents_data" |
  jq -r '.[] | [.Seeders, .Size, .TrackerId, .Title] | @tsv' |
  numfmt --to=iec --field 2 -d$'\t' |
  nl -v 0 -w 1 | 
  column --table-columns "ID,Seeder,Size,Tracker,Title" --table --separator $'\t'
)

selected_torrents="$(echo "$torrents_table" | fzf)"
selected_torrents_id="$(echo "$selected_torrents" | cut -d' ' -f1 | tr '\n' ' ')"

for selected_torrent_id in $selected_torrents_id; do
  if [ -n "$selected_torrent_id" ]; then

    magnet_link="$(echo "$torrents_data" | jq -r ".[$selected_torrent_id] | .MagnetUri")"

    if [ "$magnet_link" = "null" ]; then
      link="$(echo "$torrents_data" | jq -r ".[$selected_torrent_id] | .Link")"

      [ -n "$link" ] && magnet_link="$(wget "$link" --server-response 2>&1 | grep 'Location:' -m 1 | sed 's|Location:||')"
    fi

    echo "$magnet_link"
  fi
done
